# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build notetaker`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t notetaker`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system notetaker && \
          adduser --system -G notetaker notetaker

COPY dist/notetaker notetaker
RUN chown -R notetaker:notetaker .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix notetaker --omit=dev -f install

CMD [ "node", "notetaker" ]
